# -*- coding: utf-8 -*-
"""client.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FbSzRC6FjhOmTBsfP-R1WqLiHNyygcYU
"""

class Client:
    def __init__(self):
        pass