# -*- coding: utf-8 -*-
"""configs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kEV6vLsLINFnAEgV3MdbTt_gXhRjbTz0
"""

import os

class Configs:
    """
    Parses configuration files, stores and provides access
    to common simulator parameters and peer information.
    """
    def __init__(self, common_cfg_path, peer_info_path):
        self.common_cfg_path = common_cfg_path
        self.peer_info_path = peer_info_path
        self.piece_size = None
        self.file_name = None
        self.max_connections = None
        self.handshake_header = None
        self.file_size = None
        self.peer_info = []           # Will store tuples/lists of (peer_id, hostname, port)
        self._parse_common_cfg()
        self._parse_peer_info()

    def _parse_common_cfg(self):
        with open(self.common_cfg_path, 'r') as f:
            for line in f:
                if line.strip() and not line.startswith('#'):
                    key, value = line.strip().split('=')
                    if key == 'PieceSize':
                        self.piece_size = int(value)
                    elif key == 'FileName':
                        self.file_name = value
                        self.file_size = os.path.getsize(value) if os.path.exists(value) else 0
                    elif key == 'MaxConnections':
                        self.max_connections = int(value)
                    elif key == 'HandshakeHeader':
                        self.handshake_header = value

    def _parse_peer_info(self):
        with open(self.peer_info_path, 'r') as f:
            for line in f:
                if line.strip() and not line.startswith('#'):
                    parts = line.strip().split()
                    if len(parts) == 3:
                        peer_id = parts[0]
                        host = parts[1]
                        port = int(parts[2])
                        self.peer_info.append((peer_id, host, port))
                    else:
                        print(f"Warning: Invalid peer info line: {line.strip()}")

    def __str__(self):
        return (
            f"Configs(\n"
            f"  piece_size={self.piece_size},\n"
            f"  file_name={self.file_name},\n"
            f"  file_size={self.file_size},\n"
            f"  max_connections={self.max_connections},\n"
            f"  handshake_header={self.handshake_header},\n"
            f"  peer_info={self.peer_info}\n"
            f")"
        )