# -*- coding: utf-8 -*-
"""event.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16E6ys-oKLYu-NdEt4D3f7uBdI9fpSIZp
"""

class Event:
    def __init__(self, time, event_type, data=None):
        self.time = time
        self.event_type = event_type
        self.data = data

    def __lt__(self, other):    # Sorts event
        return self.time < other.time

    def __repr__(self):
        return f"Event(time={self.time}, type={self.event_type}, data={self.data})"