# -*- coding: utf-8 -*-
"""event_queue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZhkgVmULnz0hNKU-iY4TmuMT6euUk8LL
"""

import heapq

class EventQueue:
    def __init__(self):
        self._queue = []

    def push(self, event):
        heapq.heappush(self._queue, event)

    def pop(self):
        if self._queue:
            return heapq.heappop(self._queue)
        return None

    def is_empty(self):
        return len(self._queue) == 0