# -*- coding: utf-8 -*-
"""server.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UqgeTFG5_mcinG9N5h1KHXFcuFt1e-nx
"""

# In many P2P designs, each Peer acts as both client and server (listening).
class Server:
    def __init__(self):
        pass